# Allows HTTPRoute in istio-ingress to reference Service helloworld in sample.
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: istio-ingress-to-helloworld
  namespace: sample
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: istio-ingress
  to:
    - group: ""
      kind: Service
      name: helloworld
