# Allows HTTPRoute in east-ingress to use Service helloworld in this namespace.
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: east-ingress-to-helloworld
  namespace: sample
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: east-ingress
  to:
    - group: ""
      kind: Service
      name: helloworld
